FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y 
    curl 
    git 
    sudo 
    whiptail 
    procps 
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["tail", "-f", "/dev/null"]
